### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by CrazyCreator13** [Lyr3x/hass-Duet3D#17]
How can i find a tutorial for install this plugin in home-assistant

the readme here is not enough for me to running it correctly

**Comment by repier37** [comment]
Which steps are missing? I have enriched the readme in a pull request, you can check it out if you like, you might find some things

**Comment by CrazyCreator13** [comment]
Unclear for me: how know HASS (or better hass-Duet3d) from my printer? how safe my Printer-IP-Adresse.
How know hass-Duet3D is my my printer standalone or RPi? or in other words: how safe all this information?

**Comment by repier37** [comment]
All these informations are entered by you. In the configuration of the integration.
I guess that by "safe" you are wondering if someone can access these informations ?
These informations stays in your homeassistant instance, they are not transferred to anything. And are only used to access your printer.
So they are as safe as any other information stored in your home assistant.

**Comment by CrazyCreator13** [comment]
Mean not the security, mean how safe my IP from my Printer

**Comment by Lyr3x** [comment]
If I understand you correctly, the integration only knows that because you configure it that way. So you need to know whether you run the standalone mode or the SBC mode. If you have Raspberry Pi connected directly to your printer its SBC. 

You also need to find out your Duet's IP on your own e.g via your router.

**Comment by CrazyCreator13** [comment]
i installed all new ... now i see the pop-up with the printer info formular. now is all clear. thanks a lot
