### ISSUE TITLE
Temperatures show in fahrenheit when fahrenheit set as global temperature value.

### ISSUE THREAD

**Issue by micaheli** [Lyr3x/hass-Duet3D#23]
It sounds like expected behavior, but in HomeAssistant (something that manages your home) you want to set the unit of measurement that best suits daily activities.  For most folks in the US, and a few elsewhere, that's Fahrenheit.   Unfortunately (or maybe fortunately?) we use celcius for engineering/making activities.  Soldering temps and 3D Printing temperatures as an example, are all often referenced in celcius despite wanting to see my weather, refrigerator temperature, furnace settings, etc in Fahrenheit.  

It would be great if we could choose which temperature unit this integration uses; overriding the global value for homeassistant.

Thank you for your time.

**Comment by Cynopolis** [comment]
You can manually set these temperatures back to Celsius in home assistant by clicking on the entity>go to settings>change the unit of measurement to Celsius .

**Comment by micaheli** [comment]
How did I miss this?  Thank you SO much!

**Comment by Cynopolis** [comment]
@micaheli I'm unable to close this issue, but if this is no longer a problem then you should close it.
