### ISSUE TITLE
No connection possible

### ISSUE THREAD

**Issue by smoki3** [Lyr3x/hass-Duet3D#9]
Hi, was trying to use this integration.
But I get the following issue:

```Logger: custom_components.duet3d_printer
Source: custom_components/duet3d_printer/__init__.py:131
Integration: Duet3D Printer ([documentation](https://github.com/Lyr3x/hass-Duet3D))
First occurred: 11:48:02 (2 occurrences)
Last logged: 11:50:19

Endpoint: status Failed to update Duet status. Error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('http://192.168.1.103:80/machine/status')```

The machine is running DWC 3.4.5 an is reachable over this IP.  If it type in ` http://192.168.1.103:80/machine/status ` it does not find anything

**Comment by Lyr3x** [comment]
I assume you use the standalone mode? 
As you already clarified, the `/machine/status` endpoint is SBC exclusive.

**Comment by smoki3** [comment]
yes correct. could you please send me the output from the "/machine/status"?

With the new rr_model we should be able to get the same output on a standalone version

**Comment by Lyr3x** [comment]
https://github.com/Duet3D/RepRapFirmware/wiki/Object-Model-Documentation

The object model is documented here. Ill make that configurable and make a new release -> If it is really the object model we are good to go for both!
Maybe we can connect via discord to debug more quickly?

**Comment by smoki3** [comment]
sure no problem
